export const TOOL_CATEGORIES = [
  { id: 'organize', label: 'Organize', icon: '📄' },
  { id: 'security', label: 'Security', icon: '🔐' },
  { id: 'convert', label: 'Convert', icon: '🔄' },
  { id: 'edit', label: 'Edit', icon: '✏️' },
  { id: 'ai', label: 'AI Tools', icon: '🤖' },
]

export const TOOLS = [
  // Organize
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDF files into one seamless document.',
    icon: '🔗',
    category: 'organize',
    color: '#6471f5',
    gradient: 'from-brand-500 to-brand-700',
    endpoint: '/api/pdf/merge',
    acceptedFiles: ['.pdf'],
    multiFile: true,
    popular: true,
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Divide a PDF into separate files by pages or ranges.',
    icon: '✂️',
    category: 'organize',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-700',
    endpoint: '/api/pdf/split',
    acceptedFiles: ['.pdf'],
    options: ['byPage', 'byRange', 'everyN'],
    popular: true,
  },
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce file size while maintaining quality.',
    icon: '🗜️',
    category: 'organize',
    color: '#06d6d6',
    gradient: 'from-cyan-500 to-teal-600',
    endpoint: '/api/pdf/compress',
    acceptedFiles: ['.pdf'],
    options: ['quality'],
    popular: true,
  },
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate pages 90°, 180°, or 270° with precision.',
    icon: '🔄',
    category: 'organize',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
    endpoint: '/api/pdf/rotate',
    acceptedFiles: ['.pdf'],
    options: ['angle', 'pages'],
  },
  {
    id: 'delete-pages',
    name: 'Delete Pages',
    description: 'Remove unwanted pages from your PDF documents.',
    icon: '🗑️',
    category: 'organize',
    color: '#f43f5e',
    gradient: 'from-rose-500 to-red-600',
    endpoint: '/api/pdf/delete-pages',
    acceptedFiles: ['.pdf'],
    options: ['pageRange'],
  },
  {
    id: 'reorder-pages',
    name: 'Reorder Pages',
    description: 'Drag and drop to rearrange pages in your PDF.',
    icon: '↕️',
    category: 'organize',
    color: '#10b981',
    gradient: 'from-emerald-500 to-green-600',
    endpoint: '/api/pdf/reorder',
    acceptedFiles: ['.pdf'],
    options: ['pageOrder'],
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Pull specific pages into a new PDF file.',
    icon: '📤',
    category: 'organize',
    color: '#3b82f6',
    gradient: 'from-blue-500 to-indigo-600',
    endpoint: '/api/pdf/extract',
    acceptedFiles: ['.pdf'],
    options: ['pageRange'],
  },

  // Security
  {
    id: 'add-watermark',
    name: 'Add Watermark',
    description: 'Stamp text or image watermarks on every page.',
    icon: '💧',
    category: 'security',
    color: '#6471f5',
    gradient: 'from-brand-500 to-indigo-600',
    endpoint: '/api/pdf/watermark',
    acceptedFiles: ['.pdf'],
    options: ['text', 'opacity', 'position'],
  },
  {
    id: 'page-numbers',
    name: 'Add Page Numbers',
    description: 'Insert custom page numbers anywhere on pages.',
    icon: '🔢',
    category: 'security',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-600',
    endpoint: '/api/pdf/page-numbers',
    acceptedFiles: ['.pdf'],
    options: ['position', 'startFrom', 'format'],
  },
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt your PDF with a strong password.',
    icon: '🔐',
    category: 'security',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-yellow-600',
    endpoint: '/api/pdf/protect',
    acceptedFiles: ['.pdf'],
    options: ['password', 'permissions'],
    popular: true,
  },

  // Convert
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert DOCX to professional PDF with formatting intact.',
    icon: '📝',
    category: 'convert',
    color: '#2563eb',
    gradient: 'from-blue-600 to-blue-800',
    endpoint: '/api/convert/word-to-pdf',
    acceptedFiles: ['.doc', '.docx'],
    popular: true,
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF back to editable Word document.',
    icon: '📄',
    category: 'convert',
    color: '#1d4ed8',
    gradient: 'from-blue-700 to-indigo-700',
    endpoint: '/api/convert/pdf-to-word',
    acceptedFiles: ['.pdf'],
    popular: true,
  },
  {
    id: 'ppt-to-pdf',
    name: 'PPT to PDF',
    description: 'Convert PowerPoint slides to crisp PDF.',
    icon: '📊',
    category: 'convert',
    color: '#dc2626',
    gradient: 'from-red-600 to-rose-700',
    endpoint: '/api/convert/ppt-to-pdf',
    acceptedFiles: ['.ppt', '.pptx'],
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PPT',
    description: 'Convert PDF slides back to PowerPoint format.',
    icon: '🎨',
    category: 'convert',
    color: '#e11d48',
    gradient: 'from-rose-600 to-pink-700',
    endpoint: '/api/convert/pdf-to-ppt',
    acceptedFiles: ['.pdf'],
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Turn images into a polished PDF document.',
    icon: '🖼️',
    category: 'convert',
    color: '#059669',
    gradient: 'from-emerald-600 to-teal-700',
    endpoint: '/api/convert/jpg-to-pdf',
    acceptedFiles: ['.jpg', '.jpeg', '.png', '.webp'],
    multiFile: true,
  },
  {
    id: 'pdf-to-images',
    name: 'PDF to Images',
    description: 'Export each PDF page as high-quality images.',
    icon: '📸',
    category: 'convert',
    color: '#7c3aed',
    gradient: 'from-violet-600 to-purple-800',
    endpoint: '/api/convert/pdf-to-images',
    acceptedFiles: ['.pdf'],
    options: ['format', 'dpi'],
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert spreadsheets to perfectly formatted PDFs.',
    icon: '📈',
    category: 'convert',
    color: '#16a34a',
    gradient: 'from-green-600 to-emerald-700',
    endpoint: '/api/convert/excel-to-pdf',
    acceptedFiles: ['.xls', '.xlsx', '.csv'],
  },

  // Edit
  {
    id: 'edit-pdf',
    name: 'Edit PDF Text',
    description: 'Modify text directly within your PDF documents.',
    icon: '✏️',
    category: 'edit',
    color: '#0891b2',
    gradient: 'from-cyan-600 to-sky-700',
    endpoint: '/api/edit/text',
    acceptedFiles: ['.pdf'],
    advanced: true,
  },
  {
    id: 'annotate-pdf',
    name: 'Highlight & Annotate',
    description: 'Add highlights, comments, and annotations.',
    icon: '🖊️',
    category: 'edit',
    color: '#ca8a04',
    gradient: 'from-yellow-600 to-amber-700',
    endpoint: '/api/edit/annotate',
    acceptedFiles: ['.pdf'],
    advanced: true,
  },
  {
    id: 'digital-signature',
    name: 'Digital Signature',
    description: 'Sign documents electronically with legal validity.',
    icon: '✍️',
    category: 'edit',
    color: '#0d9488',
    gradient: 'from-teal-600 to-emerald-700',
    endpoint: '/api/edit/sign',
    acceptedFiles: ['.pdf'],
    popular: true,
    advanced: true,
  },
  {
    id: 'ocr-pdf',
    name: 'OCR – Recognize Text',
    description: 'Make scanned PDFs searchable with AI-powered OCR.',
    icon: '🔍',
    category: 'edit',
    color: '#7c3aed',
    gradient: 'from-violet-600 to-indigo-700',
    endpoint: '/api/edit/ocr',
    acceptedFiles: ['.pdf'],
    advanced: true,
  },

  // AI Tools
  {
    id: 'ai-summary',
    name: 'AI Summary',
    description: 'Get instant intelligent summaries of any document.',
    icon: '🧠',
    category: 'ai',
    color: '#6471f5',
    gradient: 'from-brand-500 to-violet-600',
    endpoint: '/api/ai/summarize',
    acceptedFiles: ['.pdf'],
    popular: true,
    isAI: true,
  },
  {
    id: 'ask-pdf',
    name: 'Ask PDF (Chat)',
    description: 'Chat with your document using GPT-4o.',
    icon: '💬',
    category: 'ai',
    color: '#06d6d6',
    gradient: 'from-cyan-500 to-teal-600',
    endpoint: '/api/ai/ask',
    acceptedFiles: ['.pdf'],
    popular: true,
    isAI: true,
  },
  {
    id: 'table-extraction',
    name: 'Table Extraction',
    description: 'Extract tables from PDFs to Excel or CSV format.',
    icon: '📋',
    category: 'ai',
    color: '#10b981',
    gradient: 'from-emerald-500 to-green-600',
    endpoint: '/api/ai/extract-tables',
    acceptedFiles: ['.pdf'],
    isAI: true,
  },
  {
    id: 'doc-classification',
    name: 'Document Classification',
    description: 'AI categorizes your document type automatically.',
    icon: '🏷️',
    category: 'ai',
    color: '#f59e0b',
    gradient: 'from-amber-500 to-orange-600',
    endpoint: '/api/ai/classify',
    acceptedFiles: ['.pdf'],
    isAI: true,
  },
  {
    id: 'resume-parsing',
    name: 'Resume Parsing',
    description: 'Extract structured data from resumes/CVs instantly.',
    icon: '👤',
    category: 'ai',
    color: '#8b5cf6',
    gradient: 'from-violet-500 to-purple-600',
    endpoint: '/api/ai/parse-resume',
    acceptedFiles: ['.pdf'],
    popular: true,
    isAI: true,
  },
  {
    id: 'translation',
    name: 'PDF Translation',
    description: 'Translate your PDF to 50+ languages using AI.',
    icon: '🌐',
    category: 'ai',
    color: '#0891b2',
    gradient: 'from-sky-500 to-blue-600',
    endpoint: '/api/ai/translate',
    acceptedFiles: ['.pdf'],
    options: ['targetLanguage'],
    isAI: true,
  },
]

export const getToolById = (id) => TOOLS.find((t) => t.id === id)
export const getToolsByCategory = (category) => TOOLS.filter((t) => t.category === category)
export const getPopularTools = () => TOOLS.filter((t) => t.popular)
export const getAITools = () => TOOLS.filter((t) => t.isAI)
